comment: off
coverage:
  status:
    project:
      default:
        target: 0%
        # adjust accordingly based on how flaky your tests are
        # this allows a 0.01% drop from the previous base commit coverage
        # threshold: 0.01%
